"""Resolution-only actor renditions, pinned to approved masters and optical bytes.

No existing pipeline, runtime catalogue or approval file is modified. Preparation
is immutable; root's later hash-bound review promotes only these new records.
"""
from __future__ import annotations

import argparse
import copy
import json
import tempfile
from dataclasses import replace
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

import ui_presentation_candidates as review
from encode import encoder_environment, save_image
from model import sha256_file, validate_record_shape
from mgjrpg02_publish import (
    ROOT, PROFILE, SPECS, Spec, MAP_PATH, REPORT_PATH, RECORD_ROOT,
    prepare_derivative, validate_output, effective_registration,
    read_json, write_json, _publish_without_overwrite,
)

REPORT = ROOT / "docs/source-assets/publication/ui-correction-actor-presentation-candidates.json"
TS = ROOT / "src/generated/uiActorPresentationArt.ts"
AUTHORITY = ROOT / "docs/source-assets/publication/ui-correction-actor-derivative-authority.json"
REFRESH = ROOT / "docs/source-assets/publication/mgjrpg-02-post-v0201-active-refresh-map.json"
SCRIPT = "scripts/art_pipeline/ui_actor_presentation_candidates.py"
PROOF_ROOT = ROOT / "docs/source-assets/production/ui-correction-actor-presentation"


def selection() -> list[tuple[Spec, dict, str]]:
    sources = read_json(MAP_PATH)["entries"]
    results = {r["stableId"]: r for r in read_json(REPORT_PATH)["entries"]}
    specs = {s.stable_id: s for s in SPECS}
    chosen = [(specs[r["stableId"]], r, results[r["stableId"]]["runtimeSha256"])
              for r in sources if r["family"] == "friend"
              or (r["family"] == "enemy" and r["runtimeStatus"] == "active")]
    refresh = next(r for r in read_json(REFRESH)["entries"] if r["stableId"] == "goblin")
    record = read_json(RECORD_ROOT / f"{refresh['recordId']}.json")
    source = ROOT / record["build"]["sourcePath"]
    with Image.open(source) as opened:
        width, height = opened.size
    row = {**refresh, "sourcePath": source.relative_to(ROOT).as_posix(),
           "sourceBytes": source.stat().st_size, "sourceWidth": width, "sourceHeight": height}
    spec = Spec("batch-28-goblin-v02-matte", "goblin", "Garden Goblin", "enemy", "active",
                "ENEMY_ART.goblin", "enemy-field-256", art_version=2)
    chosen.append((spec, row, refresh["runtimeSha256"]))
    if len(chosen) != 44 or sum(s.family == "friend" for s, _, _ in chosen) != 32:
        raise ValueError("Actor selection differs from the bounded 32 friends / 12 enemies")
    return chosen


def bind_review() -> None:
    review.REPORT, review.TS = REPORT, TS
    review.IDS = tuple(row["stableId"] for _, row, _ in selection())


def projection(entries: list[dict]) -> str:
    variants = {e["id"]: {k: e[k] for k in
                ("src", "width", "height", "format", "usage", "minDisplayPx", "maxDisplayPx", "geometry")}
                for e in entries}
    return ("// Generated by ui_actor_presentation_candidates.py. Exact-byte publication requires root review.\n"
            "export const UI_ACTOR_PRESENTATION_CANDIDATES = "
            + json.dumps(variants, ensure_ascii=False, separators=(",", ":")) + " as const;\n")


def reviewed_actor_record(record: dict, entry: dict, candidate_hash: str | None = None) -> dict:
    result = review.reviewed_record(record, entry, candidate_sha256=candidate_hash)
    approval_path = REPORT.with_name(REPORT.name.replace("candidates", "approval"))
    if result["approvalStatus"] != "approved" or not approval_path.exists():
        return result
    selected = next(row for row in read_json(approval_path)["entries"] if row["id"] == entry["id"])
    disposition = selected.get("runtimeStatus", "active")
    if disposition not in {"active", "dormant"}:
        raise ValueError("Actor review disposition must be active or dormant")
    if disposition == "dormant" and entry["id"] != "tessera-dolphin":
        raise ValueError("Only the explicitly returned Tessera reproduction may be held dormant")
    result["runtimeStatus"] = disposition
    result["derivatives"][0]["runtimeStatus"] = disposition
    return result


def publish_reviewed() -> dict:
    result = review.publish_reviewed()
    # Exact-byte authorization is shared with the established approval helper.
    # The root additionally keeps the known damaged reproduction dormant while
    # a separately reviewed r02 supplies live contextual presentation.
    for entry in read_json(REPORT)["entries"]:
        path = RECORD_ROOT / f"{entry['candidateRecordId']}.json"
        record = reviewed_actor_record(read_json(path), entry)
        write_json(path, record)
    return result


def run(check: bool) -> dict:
    bind_review()
    entries, staged_files = [], []
    with tempfile.TemporaryDirectory(prefix="maze-actor-presentation-") as temporary:
        stage = Path(temporary)
        for spec, row, optical_hash in selection():
            identity = spec.stable_id
            source, optical = ROOT / row["sourcePath"], ROOT / row["runtimePath"]
            source_record = read_json(RECORD_ROOT / f"{row['recordId']}.json")
            if source_record["approvalStatus"] != "approved" or source_record["runtimeStatus"] != "active":
                raise ValueError(f"Source authority is not currently approved and active: {identity}")
            if sha256_file(source) != row["sourceSha256"] or source.stat().st_size != row["sourceBytes"]:
                raise ValueError(f"Immutable source drift: {identity}")
            if min(row["sourceWidth"], row["sourceHeight"]) < 512:
                raise ValueError(f"Presentation must not upscale a small source: {identity}")
            prepared, _, processing = prepare_derivative(spec, row)
            rebuilt = stage / f"{identity}-optical.webp"
            save_image(prepared, rebuilt, "webp", processing["encoderOptions"])
            if rebuilt.read_bytes() != optical.read_bytes() or sha256_file(optical) != optical_hash:
                raise ValueError(f"Approved optical bytes cannot be reproduced: {identity}")
            base_profile = PROFILE[spec.profile]
            profile_id = f"{spec.family}-presentation-512"
            PROFILE[profile_id] = {**base_profile, "width": 512, "height": 512}
            candidate_spec = replace(spec, profile=profile_id)
            prepared, extraction, processing = prepare_derivative(candidate_spec, row)
            built = stage / f"{identity}-presentation.webp"
            encoder = save_image(prepared, built, "webp", processing["encoderOptions"])
            # Pixel/geometry checks still run for outputs exceeding the old 256px
            # ceiling. The inherited allocation remains red in provenance.
            inherited_ceiling = base_profile["ceiling"]
            validation_errors = []
            if built.stat().st_size > inherited_ceiling:
                validation_errors.append(f"{built.stat().st_size} bytes exceeds inherited {inherited_ceiling} byte ceiling")
            PROFILE[profile_id]["ceiling"] = max(inherited_ceiling, built.stat().st_size)
            result = validate_output(candidate_spec, row, built)
            PROFILE[profile_id]["ceiling"] = inherited_ceiling
            if result["geometry"]["class"] != source_record["geometry"]["class"]:
                raise ValueError(f"Geometry class drift: {identity}")
            path = f"public/assets/mgjrpg-02/presentation/{identity}-v{row['artVersion']:02d}-presentation-512-r01.webp"
            record_id = f"{identity}-ui-correction-presentation-candidate-r01-source"
            record_path = RECORD_ROOT / f"{record_id}.json"
            record = copy.deepcopy(source_record)
            record.update(recordId=record_id, approvalStatus="candidate", runtimeStatus="dormant",
                          derivativeRecipeVersion="ui-correction-approved-actor-presentation-r01",
                          geometry=result["geometry"])
            record.pop("approvalEvidence", None)
            record["knownUnknowns"].append("512px candidate only; root must inspect contextual/alpha proofs and approve exact incremental media bytes before publication.")
            record["humanEdits"] = [{"kind": "deterministic-delivery-processing", "script": SCRIPT,
                "description": "Rebuilt approved optical bytes exactly, then applied the same approved source extraction and family registration at 512px. No generated redraw, source alteration or optical upscale."}]
            optical_derivative = next(d for d in source_record["derivatives"] if d["path"] == row["runtimePath"])
            record["derivatives"] = [{**optical_derivative, "id": f"{identity}-{profile_id}-r01", "path": path,
                **{k: result[k] for k in ("sha256", "bytes", "width", "height", "format", "mode", "alphaMode", "decodedBytesUpperBound")},
                "profile": profile_id, "runtimeStatus": "dormant", "loadingPhase": "visible-contextual-presentation-only",
                "encoder": {k: encoder[k] for k in ("name", "version", "options")}}]
            record["build"]["profiles"] = [{"id": profile_id, "outputPath": path, "width": 512, "height": 512,
                "format": "webp", "maxEncodedBytes": inherited_ceiling, "encoder": {"options": processing["encoderOptions"]}}]
            record["rollback"] = {"method": "Remove the actor presentation extension from the UI catalogue. Original approved optical assets and their records remain unchanged and available."}
            errors = validate_record_shape(record, record_id)
            if errors:
                raise ValueError(errors)
            staged_record = stage / record_path.name
            write_json(staged_record, record)
            bounds = result["geometry"]["visibleBounds"]
            entry = {"id": identity, "label": row["label"], "family": spec.family,
                "approvalStatus": "candidate", "sourceRecordId": row["recordId"],
                "sourcePath": row["sourcePath"], "sourceSha256": row["sourceSha256"], "sourceBytes": row["sourceBytes"],
                "sourceSize": [row["sourceWidth"], row["sourceHeight"]], "opticalUrl": row["publicUrl"],
                "opticalSha256": optical_hash, "opticalReproduced": True, "candidateRecordId": record_id,
                "path": path, "src": "/" + path.removeprefix("public/"), "usage": "presentation", "profile": profile_id,
                "minDisplayPx": 96, "maxDisplayPx": 256, **result, "extraction": extraction,
                "registration": effective_registration(candidate_spec, PROFILE[profile_id]), "encoder": encoder,
                "validationErrors": validation_errors, "inheritedPerFileCeiling": inherited_ceiling,
                "visibleSubjectAt200": max(bounds[2:]) * 200, "visibleSubjectAt256": max(bounds[2:]) * 256}
            entries.append(entry)
            if check:
                write_json(staged_record, reviewed_actor_record(record, entry, sha256_file(staged_record)))
            for staged, destination in ((built, ROOT / path), (staged_record, record_path)):
                if check:
                    if not destination.is_file() or staged.read_bytes() != destination.read_bytes():
                        raise ValueError(f"Candidate byte drift: {destination}")
                else:
                    if destination.exists():
                        raise FileExistsError(destination)
                    staged_files.append((staged, destination))
            print(f"{identity}: optical exact; {result['bytes']} bytes; {result['geometry']['class']}", flush=True)
        report = {"schema": "maze-ui-presentation-candidate/v1", "authority": AUTHORITY.relative_to(ROOT).as_posix(),
            "authoritySha256": sha256_file(AUTHORITY), "sourceMapSha256": sha256_file(MAP_PATH),
            "refreshMapSha256": sha256_file(REFRESH), "approvalStatus": "candidate", "preparedOn": "2026-09-05",
            "environment": encoder_environment(), "runtimeBytes": sum(e["bytes"] for e in entries),
            "decodedBytesUpperBound": sum(e["decodedBytesUpperBound"] for e in entries),
            "gate": "Root visual review and exact measured allocation required; candidate metadata does not approve runtime publication.",
            "entries": entries}
        content = projection(entries)
        if check:
            if read_json(REPORT) != report or TS.read_text(encoding="utf-8") != content:
                raise ValueError("Candidate report or projection drift")
        else:
            if REPORT.exists() or TS.exists():
                raise FileExistsError("Candidate report or projection already exists")
            for staged, destination in staged_files:
                destination.parent.mkdir(parents=True, exist_ok=True)
                _publish_without_overwrite(staged, destination)
            write_json(REPORT, report)
            TS.write_text(content, encoding="utf-8")
    return {"checked": len(entries), "runtimeBytes": report["runtimeBytes"],
            "perFileAllocationRequests": sum(bool(e["validationErrors"]) for e in entries)}


def make_proofs() -> dict:
    """Inspect every rendition on warm and dark surfaces at 208px display size."""
    report = read_json(REPORT)
    font = ImageFont.load_default(size=15)
    proofs = []
    for palette, background, ink in (("light", "#fff5db", "#392f51"), ("dark", "#302c46", "#fff5db")):
        for page in range(2):
            entries = report["entries"][page * 22:(page + 1) * 22]
            sheet = Image.new("RGB", (1380, 1116), background)
            draw = ImageDraw.Draw(sheet)
            draw.text((16, 12), f"Approved-source actor presentation | {palette} | page {page + 1} | 208px display", fill=ink, font=font)
            for index, entry in enumerate(entries):
                x, y = 14 + index % 6 * 228, 40 + index // 6 * 266
                with Image.open(ROOT / entry["path"]) as opened:
                    art = opened.convert("RGBA")
                # Premultiplied resizing retains correct transparent edge color.
                from cutout import premultiplied_resize
                art = premultiplied_resize(art, (208, 208))
                sheet.paste(art, (x + 10, y), art)
                label = entry["label"]
                if len(label) > 23:
                    split = label.rfind(" ", 0, 23)
                    label = label[:split] + "\n" + label[split + 1:] if split > 0 else label
                draw.text((x + 8, y + 210), label, fill=ink, font=font)
                draw.text((x + 8, y + 246), f"{entry['bytes']:,} bytes", fill=ink, font=font)
            path = PROOF_ROOT / f"actor-presentation-{palette}-{page + 1:02d}.png"
            if path.exists():
                raise FileExistsError(path)
            path.parent.mkdir(parents=True, exist_ok=True)
            save_image(sheet, path, "png", {"compress_level": 9, "optimize": False})
            proofs.append({"path": path.relative_to(ROOT).as_posix(), "sha256": sha256_file(path), "bytes": path.stat().st_size})
    result = {"schema": "maze-actor-presentation-proof/v1", "candidateReportSha256": sha256_file(REPORT),
              "displayPx": 208, "reviewStatus": "root-visual-review-pending", "proofs": proofs}
    write_json(PROOF_ROOT / "proof-index.json", result)
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--prepare", action="store_true")
    group.add_argument("--check", action="store_true")
    group.add_argument("--publish-reviewed", action="store_true")
    group.add_argument("--proof", action="store_true")
    args = parser.parse_args()
    bind_review()
    print(json.dumps(make_proofs() if args.proof else publish_reviewed() if args.publish_reviewed else run(args.check), indent=2))
