"""Bounded Plan01 candidate derivatives from fourteen already-approved masters.

Never generate art or rewrite historical publication/approval records. --prepare
uses no-replace publication; --check rebuilds and compares bytes. Candidate
approval stays explicit: public outputs intentionally require root's art gate.
"""
from __future__ import annotations

import argparse
import copy
import json
import tempfile
from dataclasses import replace
from pathlib import Path
from PIL import Image
from builder import alpha_bounds
from model import image_facts, validate_record_shape

from mgjrpg02_publish import (
    ROOT, PROFILE, SPECS, MAP_PATH, REPORT_PATH, RECORD_ROOT,
    prepare_derivative, validate_output, effective_registration, alpha_weighted_visual_center,
    read_json, sha256_file, write_json, _publish_without_overwrite,
)
from encode import save_image, encoder_environment

IDS = (
    "star-sword", "flower-sabre", "moon-wand", "leaf-blade", "sun-mallet",
    "comet-spear", "bubble-ring-blade", "cupcake-mace", "key-rose-heart",
    "key-sunny-sun", "key-blue-star", "splash-boots", "spring-boots", "antidote-leaf",
)
PROFILE_ID = "prop-presentation-512"
BASE_PROFILE_ID = "prop-field-256"
REPORT = ROOT / "docs/source-assets/publication/ui01-presentation-candidates.json"
TS = ROOT / "src/generated/uiPresentationArt.ts"
AUTHORITY = "docs/plans/AGENT01-review-follow-up.md"
EXPORT_NAME = "UI_PRESENTATION_CANDIDATES"


def projection(entries: list[dict]) -> str:
    variants = {e["id"]:{k:e[k] for k in ("src","width","height","format","usage","minDisplayPx","maxDisplayPx","geometry")} for e in entries}
    # The candidate snapshot remains byte-identical as preparation evidence.
    # Current publication authority is the separate hash-bound approval record.
    return "// Generated by ui_presentation_candidates.py. Candidate derivatives, root review pending.\nexport const " + EXPORT_NAME + " = " + json.dumps(variants,ensure_ascii=False,separators=(",",":")) + " as const;\n"


def reviewed_record(record: dict, entry: dict, *, candidate_sha256: str | None = None) -> dict:
    """Apply only an exact-byte, separately recorded root publication decision."""
    decision_path = REPORT.with_name(REPORT.name.replace("candidates", "approval"))
    if not decision_path.exists():
        return record
    decision = read_json(decision_path)
    if decision.get("schema") != "maze-ui-presentation-approval/v1" or decision.get("scope") != "runtime-publish":
        raise ValueError("Invalid presentation approval scope")
    if decision.get("candidateReportSha256") != sha256_file(REPORT):
        raise ValueError("Presentation approval does not match candidate evidence")
    approved = decision.get("entries", [])
    if len(approved) != len(IDS) or {row["id"] for row in approved} != set(IDS):
        raise ValueError("Presentation approval identity set mismatch")
    matches = [row for row in approved if row["id"] == entry["id"]]
    if len(matches) != 1:
        raise ValueError("Missing or duplicate presentation approval")
    selected = matches[0]
    if candidate_sha256 is not None and selected.get("candidateRecordSha256") != candidate_sha256:
        raise ValueError("Approved candidate provenance hash mismatch")
    for key in ("path", "sha256", "bytes", "sourceSha256"):
        if selected.get(key) != entry.get(key):
            raise ValueError(f"Presentation approval {key} mismatch: {entry['id']}")
    ceiling = selected.get("maxEncodedBytes")
    if not isinstance(ceiling, int) or ceiling < entry["bytes"]:
        raise ValueError("Approved presentation byte ceiling is insufficient")
    result = copy.deepcopy(record)
    result["approvalStatus"] = "approved"
    result["runtimeStatus"] = "active"
    result["derivatives"][0]["runtimeStatus"] = "active"
    result["build"]["profiles"][0]["maxEncodedBytes"] = ceiling
    result["approvalEvidence"] = {
        "approvedBy": decision["approvedBy"], "approvedAt": decision["approvedAt"],
        "scope": "runtime-publish", "evidencePath": decision_path.relative_to(ROOT).as_posix(),
        "evidenceSha256": sha256_file(decision_path),
    }
    result["knownUnknowns"] = [note for note in result["knownUnknowns"] if not note.startswith("512px candidate only;")]
    errors = validate_record_shape(result, result["recordId"])
    if errors:
        raise ValueError(errors)
    return result


def publish_reviewed() -> dict:
    """Promote metadata only, after checking every reviewed source/output hash."""
    report = read_json(REPORT)
    decision_path = REPORT.with_name(REPORT.name.replace("candidates", "approval"))
    decision = read_json(decision_path)
    approved_entries = {entry["id"]: entry for entry in decision["entries"]}
    changes = []
    for entry in report["entries"]:
        for path_key, hash_key in (("path", "sha256"), ("sourcePath", "sourceSha256")):
            if sha256_file(ROOT / entry[path_key]) != entry[hash_key]:
                raise ValueError(f"Publication input drift: {entry['id']}")
        record_path = RECORD_ROOT / f"{entry['candidateRecordId']}.json"
        original = read_json(record_path)
        if original["id"] != entry["id"] or original["geometry"] != entry["geometry"]:
            raise ValueError("Candidate identity/geometry drift before publication")
        if original["approvalStatus"] == "candidate":
            if sha256_file(record_path) != approved_entries[entry["id"]]["candidateRecordSha256"]:
                raise ValueError("Candidate provenance drift before publication")
        elif original.get("approvalEvidence", {}).get("evidenceSha256") != sha256_file(decision_path):
            raise ValueError("Existing publication does not match this decision")
        updated = reviewed_record(original, entry)
        if updated["approvalStatus"] != "approved":
            raise ValueError("Named root approval is required before publication")
        changes.append((record_path, updated))
    # Validate the entire batch before any write; never replace public pixels.
    for path, record in changes:
        write_json(path, record)
    return {"publishedRecords": len(changes), "pixelsChanged": 0}


def refresh_metadata() -> dict:
    """One bounded migration of this task's unapproved metadata; never pixels."""
    report = read_json(REPORT)
    if report["approvalStatus"] != "candidate" or report["authoritySha256"] != sha256_file(ROOT/AUTHORITY):
        raise ValueError("Candidate authority changed; root review required")
    for entry in report["entries"]:
        identity = entry["id"]
        if identity not in IDS or sha256_file(ROOT/entry["path"]) != entry["sha256"]:
            raise ValueError("Candidate pixel drift")
        old_path = RECORD_ROOT / f"{identity}-ui01-presentation-candidate-r01.json"
        new_id = f"{identity}-ui01-presentation-candidate-r01-source"
        new_path = RECORD_ROOT / f"{new_id}.json"
        if new_path.exists(): raise FileExistsError(new_path)
        record = read_json(old_path)
        if record["approvalStatus"] != "candidate": raise ValueError("Not this task's candidate")
        if entry["geometry"]["class"] == "item":
            with Image.open(ROOT/entry["path"]) as image:
                entry["geometry"]["visualCenter"] = alpha_weighted_visual_center(image.convert("RGBA"))
        entry["candidateRecordId"] = new_id
        record.update(recordId=new_id,geometry=entry["geometry"])
        errors = validate_record_shape(record,new_id)
        if errors: raise ValueError(errors)
        old_path.rename(new_path)
        write_json(new_path,record)
    write_json(REPORT,report); TS.write_text(projection(report["entries"]),encoding="utf-8")
    return {"metadataCorrected":len(report["entries"]),"pixelsChanged":0}


def run(check: bool) -> dict:
    # The only recipe change is output resolution. Inherited per-file guard
    # remains in force; this does NOT grant any aggregate byte allocation.
    PROFILE[PROFILE_ID] = {**PROFILE[BASE_PROFILE_ID], "width": 512, "height": 512}
    sources = {r["stableId"]: r for r in read_json(MAP_PATH)["entries"]}
    old_results = {r["stableId"]: r for r in read_json(REPORT_PATH)["entries"]}
    specs = {s.stable_id: s for s in SPECS}
    entries, staged_files = [], []
    with tempfile.TemporaryDirectory(prefix="ui01-presentation-") as temporary:
        stage = Path(temporary)
        for identity in IDS:
            row, spec = sources[identity], specs[identity]
            source = ROOT / row["sourcePath"]
            if sha256_file(source) != row["sourceSha256"] or source.stat().st_size != row["sourceBytes"]:
                raise ValueError(f"Immutable source drift: {identity}")
            optical = ROOT / row["runtimePath"]
            prepared, _, processing = prepare_derivative(spec, row)
            rebuilt = stage / f"{identity}-optical.webp"
            save_image(prepared, rebuilt, "webp", processing["encoderOptions"])
            if rebuilt.read_bytes() != optical.read_bytes() or sha256_file(optical) != old_results[identity]["runtimeSha256"]:
                raise ValueError(f"Cannot reproduce approved optical bytes: {identity}")
            candidate_spec = replace(spec, profile=PROFILE_ID)
            prepared, extraction, processing = prepare_derivative(candidate_spec, row)
            built = stage / f"{identity}-presentation.webp"
            encoder = save_image(prepared, built, "webp", processing["encoderOptions"])
            validation_errors = []
            try:
                result = validate_output(candidate_spec, row, built)
            except ValueError as error:
                # Preserve a red per-file byte gate while preparing review
                # evidence. Pixel/alpha errors are not recoverable here.
                if "bytes exceeds" not in str(error): raise
                validation_errors.append(str(error))
                with Image.open(built) as image:
                    bounds = alpha_bounds(image,3)
                    x0,y0,x1,y1 = bounds["pixelsLTRB"]
                geometry = {**old_results[identity]["geometry"],
                    "visibleBounds":[x0/512,y0/512,(x1-x0)/512,(y1-y0)/512],
                    "safeInset":[y0/512,(512-x1)/512,(512-y1)/512,x0/512]}
                if geometry["class"] == "icon":
                    geometry["opticalBounds"] = list(geometry["visibleBounds"])
                if geometry["class"] == "item":
                    with Image.open(built) as image:
                        geometry["visualCenter"] = alpha_weighted_visual_center(image.convert("RGBA"))
                result = {**image_facts(built),"bytes":built.stat().st_size,"sha256":sha256_file(built),
                    "geometry":geometry,"alphaBounds":bounds}
            bound = result["geometry"]["visibleBounds"]
            if max(bound[2:]) * 200 < 144 or max(bound[2:]) * 128 < 96:
                raise ValueError(f"Subject too small: {identity}")
            path = f"public/assets/mgjrpg-02/presentation/{identity}-v{row['artVersion']:02d}-presentation-512-r01.webp"
            record_id = f"{identity}-ui01-presentation-candidate-r01-source"
            record_path = RECORD_ROOT / f"{record_id}.json"
            record = copy.deepcopy(read_json(RECORD_ROOT / f"{row['recordId']}.json"))
            record.update(recordId=record_id, approvalStatus="candidate", runtimeStatus="dormant",
                          derivativeRecipeVersion="ui01-approved-source-presentation-r01", geometry=result["geometry"])
            record.pop("approvalEvidence", None)
            record["knownUnknowns"].append("512px candidate only; root must review actual-size/alpha proofs and approve incremental bytes. Source approval does not approve this derivative.")
            record["humanEdits"] = [{"kind":"deterministic-delivery-processing", "description":"Same approved extraction and normalized registration at 512px; optical output first rebuilt byte-exactly. No redraw or source changes.", "script":"scripts/art_pipeline/ui_presentation_candidates.py"}]
            record["derivatives"] = [{**record["derivatives"][0], "id":f"{identity}-{PROFILE_ID}-r01", "path":path,
                **{k:result[k] for k in ("sha256","bytes","width","height","format","mode","alphaMode","decodedBytesUpperBound")},
                "profile":PROFILE_ID, "runtimeStatus":"dormant", "loadingPhase":"visible-contextual-presentation-only",
                "encoder":{k:encoder[k] for k in ("name","version","options")}}]
            profile = record["build"]["profiles"][0]
            profile.update(id=PROFILE_ID, outputPath=path, width=512, height=512)
            record["rollback"] = {"method":"Remove this candidate catalogue extension from UI; unchanged approved optical URLs remain the fallback. Retain source and derivative until root retirement authority."}
            errors = validate_record_shape(record,record_id)
            if errors: raise ValueError(errors)
            staged_record = stage / record_path.name
            write_json(staged_record, record)
            entry = {"id":identity, "label":row["label"], "approvalStatus":"candidate", "sourceRecordId":row["recordId"],
                "sourcePath":row["sourcePath"], "sourceSha256":row["sourceSha256"], "sourceBytes":row["sourceBytes"],
                "sourceSize":[row["sourceWidth"],row["sourceHeight"]], "opticalUrl":row["publicUrl"],
                "opticalSha256":sha256_file(optical), "opticalReproduced":True, "candidateRecordId":record_id,
                "path":path, "src":"/"+path.removeprefix("public/"), "usage":"presentation", "profile":PROFILE_ID,
                "minDisplayPx":96,"maxDisplayPx":256, **result, "extraction":extraction,
                "registration":effective_registration(candidate_spec,PROFILE[PROFILE_ID]), "encoder":encoder,
                "validationErrors":validation_errors, "inheritedPerFileCeiling":PROFILE[PROFILE_ID]["ceiling"],
                "visibleSubjectAt200":max(bound[2:])*200, "visibleSubjectAt128":max(bound[2:])*128}
            entries.append(entry)
            if check:
                write_json(staged_record, reviewed_record(record, entry, candidate_sha256=sha256_file(staged_record)))
            for staged, destination in [(built,ROOT/path),(staged_record,record_path)]:
                if check:
                    if not destination.is_file() or staged.read_bytes() != destination.read_bytes():
                        raise ValueError(f"Candidate byte drift: {destination}")
                else:
                    if destination.exists(): raise FileExistsError(destination)
                    staged_files.append((staged,destination))
            print(f"{identity}: optical exact; candidate {result['bytes']} bytes; subject {entry['visibleSubjectAt200']:.2f}/{entry['visibleSubjectAt128']:.2f}px", flush=True)
        report = {"schema":"maze-ui-presentation-candidate/v1", "authority":AUTHORITY,
            "authoritySha256":sha256_file(ROOT/AUTHORITY), "sourceMapSha256":sha256_file(MAP_PATH),
            "approvalStatus":"candidate", "preparedOn":"2026-09-05", "environment":encoder_environment(),
            "runtimeBytes":sum(e["bytes"] for e in entries), "decodedBytesUpperBound":sum(e["decodedBytesUpperBound"] for e in entries),
            "gate":"Root art proof and allocation approval required; unapproved-runtime-output remains an intentional unwaived art gate.", "entries":entries}
        content = projection(entries)
        if check:
            if read_json(REPORT) != report or TS.read_text(encoding="utf-8") != content: raise ValueError("Candidate report/projection drift")
        else:
            if REPORT.exists() or TS.exists(): raise FileExistsError("Candidate report/projection already exists")
            for staged,destination in staged_files:
                destination.parent.mkdir(parents=True,exist_ok=True); _publish_without_overwrite(staged,destination)
            write_json(REPORT,report); TS.write_text(content,encoding="utf-8")
    return {"checked":len(entries),"runtimeBytes":report["runtimeBytes"],
            "publicationReviewed":REPORT.with_name(REPORT.name.replace("candidates", "approval")).exists()}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--prepare",action="store_true"); group.add_argument("--check",action="store_true")
    group.add_argument("--refresh-metadata",action="store_true")
    group.add_argument("--publish-reviewed",action="store_true")
    parser.add_argument("--rewards",action="store_true",help="Root-scoped fifteen earned-reward derivatives")
    args=parser.parse_args()
    if args.rewards:
        AUTHORITY = "docs/source-assets/publication/ui01-reward-derivative-authority.json"
        IDS = tuple(read_json(ROOT / AUTHORITY)["ids"])
        PROFILE_ID, BASE_PROFILE_ID = "reward-presentation-512", "reward-presentation-256"
        REPORT = ROOT / "docs/source-assets/publication/ui01-reward-presentation-candidates.json"
        TS = ROOT / "src/generated/uiRewardPresentationArt.ts"
        EXPORT_NAME = "UI_REWARD_PRESENTATION_CANDIDATES"
        if args.refresh_metadata:
            raise ValueError("Historical equipment metadata repair does not apply to rewards")
    print(json.dumps(publish_reviewed() if args.publish_reviewed else refresh_metadata() if args.refresh_metadata else run(args.check),indent=2))
