import type { AnimalSpecies, EnemyStyle } from "./game/types";

/** Short Puzzlewild flavour, separate from the engine's rules and reward descriptions. */
export const FRIEND_BOOK_LORE: Readonly<Record<AnimalSpecies, string>> = {
  bunny: "Keeps a list of excellent picnic spots. Most of the list is little drawings of carrots.",
  fox: "Always notices a new path. Always stops to admire an interesting leaf along it.",
  kitten: "Inspects every map by sitting on the most important corner. Poggle calls this careful research.",
  puppy: "Has never met a homecoming that did not deserve a very enthusiastic tail wag.",
  duckling: "Practises a splendid little parade march, then forgets the march when a puddle appears.",
  hedgehog: "Brings the smallest blanket to every picnic and somehow finds room for a friend.",
  fawn: "Steps softly through the gardens, pausing whenever a butterfly has something to show.",
  "red-panda": "Can balance on a branch while deciding which snack to eat. Deciding is the difficult part.",
  otter: "Collects smooth pebbles and gives the very nicest ones to friends.",
  lamb: "Looks like a little cloud that wandered down for a better view of the flowers.",
  capybara: "Enjoys a quiet corner of the picnic. Everyone is welcome to be quiet there together.",
  chinchilla: "Those magnificent ears are particularly good at hearing the word 'snack'.",
  alpaca: "Wears a proud little smile, even when the parade accidentally goes around the same tree twice.",
  penguin: "Takes small, determined steps. Arriving together matters much more than arriving first.",
  koala: "Has an excellent plan for the afternoon: a gentle adventure, then a very comfortable nap.",
  "pitter-patter-parasol": "Loves the sound of rain on a roof. Sunny days are lovely too, but much quieter.",
  lanternling: "Dreams of joining the lantern festival. Has already practised a very welcoming glow.",
  "emberdown-phoenix": "Proudly calls every sunrise 'a family resemblance'. Sprig thinks this is probably right.",
  "meadowstep-faunling": "Makes up a new dance for each meadow. Sometimes the daisies appear to join in.",
  "minerva-moon-owl": "Enjoys thoughtful questions, moonlit stories, and correcting Poggle's upside-down bookmarks.",
  "tessera-dolphin": "Imagines the paths as little rivers and every homecoming as a beautiful splash.",
  "mallowmusk-aroma-wisp": "A soft little puff with grand ideas about perfume. Today's idea is 'picnic in a cloud'.",
  "breezeling-sylph": "Giggles whenever a breeze turns a page before Poggle has finished reading it.",
  "griffin-cub": "Practises looking majestic. The effect is slightly spoiled by the urge to pounce on ribbons.",
  "emberbelly-dragonling": "Has a warm, rumbly laugh and a collection of extremely small heroic poses.",
  "cloudstep-pegasus": "Loves a clear morning and the sort of story that ends with everybody coming home.",
  "three-tumble-cerberus": "Three heads, three opinions about snacks, and one very happy tail.",
  "riddlekit-sphinx": "Asks tiny riddles at teatime. Sometimes the answer is 'another biscuit'.",
  "tidecurl-hippocamp": "Carries the feeling of a seaside holiday wherever the little paths happen to lead.",
  "ripplecap-kappa": "Insists that a proper picnic needs cucumber sandwiches. Packs enough to share.",
  "rainbow-horn-unicorn": "Thinks a rainbow is a very good reason to stop for a moment and look up.",
  "green-tea-skeleton": "Takes tea very seriously and everything else rather cheerfully. There is always time for another cup.",
};

export const ENEMY_BOOK_LORE: Readonly<Record<EnemyStyle, string>> = {
  goblin: "A very enthusiastic garden guardian. Rehearses a grand entrance, then forgets where to stand.",
  "blueberry-slime": "Wobbles proudly at its post. Even its most serious face looks a little like a pudding.",
  "mushroom-imp": "Treats its splendid mushroom cap as a ceremonial hat. Would quite like everyone to notice.",
  "moon-bat": "Practises elegant moonlit swoops and occasionally applauds itself with its own wings.",
  "pebble-golem": "Stands as still as a statue until something funny happens. Then its shoulders begin to rumble.",
  "acorn-knight": "An earnest little guardian with very polished manners and an impressively important acorn helmet.",
  "bubble-dragon": "Makes a brave face, then gets distracted admiring a particularly round bubble.",
  "candy-mimic": "Has practised a spectacular surprised expression. Being a chest makes rehearsals rather cramped.",
  "cloud-gremlin": "Enjoys dramatic entrances. A small cloud is apparently essential to the performance.",
  "pumpkin-sprite": "Considers every evening a fine occasion for a lantern party and a little hop.",
  "clockwork-crab": "Keeps a very orderly watch. Its sideways parade is punctual in both directions.",
  "jelly-sorcerer": "Has a serious interest in grand magical gestures. Holding a serious shape is another matter.",
};
