import type { AnimalSpecies, EnemyStyle } from "./game/types";
// Frozen obtainable release roster; source placements are audited in
// docs/reviews/2026-09-06-plan09-p0-obtainable-roster.md. Do not derive from enums.
export const BOOK_ROSTER_REVISION = "obtainable-20260906";
export const BOOK_FRIEND_IDS = [
  "bunny",
  "fox",
  "kitten",
  "puppy",
  "duckling",
  "hedgehog",
  "fawn",
  "red-panda",
  "otter",
  "lamb",
  "capybara",
  "chinchilla",
  "alpaca",
  "penguin",
  "koala",
  "pitter-patter-parasol",
  "lanternling",
  "emberdown-phoenix",
  "meadowstep-faunling",
  "minerva-moon-owl",
  "tessera-dolphin",
  "mallowmusk-aroma-wisp",
  "breezeling-sylph",
  "griffin-cub",
  "emberbelly-dragonling",
  "cloudstep-pegasus",
  "three-tumble-cerberus",
  "riddlekit-sphinx",
  "tidecurl-hippocamp",
  "ripplecap-kappa",
  "rainbow-horn-unicorn",
  "green-tea-skeleton",
] as const satisfies readonly AnimalSpecies[];
export const BOOK_GUARDIAN_IDS = [
  "goblin",
  "blueberry-slime",
  "mushroom-imp",
  "moon-bat",
  "pebble-golem",
  "acorn-knight",
  "bubble-dragon",
  "candy-mimic",
  "cloud-gremlin",
  "pumpkin-sprite",
  "clockwork-crab",
  "jelly-sorcerer",
] as const satisfies readonly EnemyStyle[];
